feat: Allow scope param on user alias requests
mParticle/mparticle-web-sdk pull request #160
Opened 2021-07-29 01:41 UTC by luads

## Summary
In some scenarios, it might be necessary to define the alias scope to something other than the default "device" option. This is not allowed on the web SDK at the moment, even though it is on the Identity API.

## Testing Plan
It's been unit tested, with user testing in progress. 

I didn't change the `convertAliasToNative` method as I'm not aware if the native clients support this param.

## Questions
- What else needs change? Docs, TypeScript types, etc.

2021-07-29 16:44 UTC, rmi22186 commented
Thanks so much for the well thought out PR @luads...you even got in a TS def which is fantastic!  🎉 

I'll have to double check with our native guys to determine if there should be a change with `convertAliasToNative`, and get back to you. I'd rather include that as a new commit if necessary rather than adding it as a new PR.

2021-07-29 23:50 UTC, luads commented
No worries at all @rmi22186, this will be quite helpful for us. Happy to raise a new PR for the native bits if needed later on.

2021-07-30 16:25 UTC, rmi22186 requested changes
Well done!  Props for figuring out how the mocking works by looking a other tests!  Only 1 comment, which really is on us to document better.  

Can you remove the updates to the `dist` folder from the commit?  This will automatically be generated when we release the SDK via our Github Action.  This way our PRs a bit cleaner :)

Otherwise looks great.

2021-07-30 16:27 UTC, rmi22186 commented
> No worries at all @rmi22186, this will be quite helpful for us. Happy to raise a new PR for the native bits if needed later on.

It appears it's not in native.  I can add an internal ticket for this...if it's a blocker for you, you can definitely PR their too, but no pressure :)

2021-07-31 05:44 UTC, luads commented
Thanks for the review @rmi22186! That makes total sense. I had to add the changes to the dist files to test it out, but I've removed them now.

As for the native implementation, we don't need that at the moment. If we do in the future, I'll give it a go :)

2021-08-02 13:57 UTC, rmi22186 approved these changes
Perfect!  Approving and merging.  We will run a release on Wednesday with a few other items we have teed up.

2021-08-02 13:58 UTC, merged

2021-08-04 14:10 UTC, mparticle-automation commented
:tada: This PR is included in version 2.14.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@mparticle/web-sdk/v/2.14.0)
- [GitHub release](https://github.com/mParticle/mparticle-web-sdk/releases/tag/v2.14.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: