ci: Add Pre-release action to synchronize branches
mParticle/mparticle-web-sdk pull request #804
Opened 2023-11-20 18:12 UTC by alexs-mparticle

## Instructions
 1. PR target branch should be against `development`
 2. PR title name should follow this format: https://github.com/mParticle/mparticle-workflows/blob/main/.github/workflows/pr-title-check.yml
 3. PR branch prefix should follow this format: https://github.com/mParticle/mparticle-workflows/blob/main/.github/workflows/pr-branch-check-name.yml

 ## Summary
 - {provide a thorough description of the changes}

 ## Testing Plan
 - [ ] Was this tested locally? If not, explain why.
 - {explain how this has been tested, and what, if any, additional testing should be done}

 ## Reference Issue (For mParticle employees only.  Ignore if you are an outside contributor)
 - Closes https://go.mparticle.com/work/REPLACEME

2023-11-20 20:53 UTC, alexs-mparticle commented on .github/workflows/synchronize-branches.yml
> +          if: ${{ github.event.inputs.dryRun == 'false' }}
```suggestion
          if: ${{ github.event.inputs.dryRun == false }}
```

2023-11-20 20:53 UTC, alexs-mparticle commented on .github/workflows/synchronize-branches.yml
> +          if: ${{ github.event.inputs.dryRun == 'false' }}
```suggestion
          if: ${{ github.event.inputs.dryRun == false }}
```

2023-11-20 20:53 UTC, alexs-mparticle commented on .github/workflows/synchronize-branches.yml
> +          if: ${{ github.event.inputs.dryRun == 'false' }}
```suggestion
          if: ${{ github.event.inputs.dryRun == false }}
```

2023-11-20 20:53 UTC, alexs-mparticle commented on .github/workflows/synchronize-branches.yml
> +          if: ${{ github.event.inputs.dryRun }}
```suggestion
          if: ${{ github.event.inputs.dryRun == false }}
```

2023-11-20 20:53 UTC, alexs-mparticle commented on .github/workflows/synchronize-branches.yml
> +          if: ${{ github.event.inputs.dryRun }}
```suggestion
          if: ${{ github.event.inputs.dryRun == false }}
```

2023-11-21 13:00 UTC, rmi22186 requested changes
Mostly nits, but looks great overall.

2023-11-21 13:03 UTC, rmi22186 commented
The commit name should also probably not be `Pre-release`, as it is the actual CDN release step.

2023-11-21 15:41 UTC, rmi22186 approved these changes

2023-11-21 15:42 UTC, merged