feat: Implement fetching user audiences
mParticle/mparticle-web-sdk pull request #841
Opened 2024-02-09 21:33 UTC by rmi22186

## Instructions
 1. PR target branch should be against `development`
 2. PR title name should follow this format: https://github.com/mParticle/mparticle-workflows/blob/main/.github/workflows/pr-title-check.yml
 3. PR branch prefix should follow this format: https://github.com/mParticle/mparticle-workflows/blob/main/.github/workflows/pr-branch-check-name.yml

 ## Summary
This PR provides for a new API on the current user: mParticle.Identity.getCurrentUser().getUserAudiences(callback).

The url it accesses is: https://jssdks.mparticle.com/v1/{apikey}/audiences?mpid=3984273492347328 and will return to the user the following schema to a callback:

```
{
  currentAudiences: Audience[],
  pastAudiences: Audience[]
}
```

 ## Testing Plan
 - [] Was this tested locally? If not, explain why.
We are waiting for the backend to be updated before 

 ## Reference Issue (For mParticle employees only.  Ignore if you are an outside contributor)
 - Closes https://go.mparticle.com/work/SQDSDKS-5994

2024-02-12 14:38 UTC, alexs-mparticle requested changes

2024-02-12 14:38 UTC, alexs-mparticle commented on src/audienceManager.ts
> +export interface IAudienceServerResponse {
We should append the word `Minified` to these interfaces just so we can differentiate from the "Full" interfaces if we ever implement them.

2024-02-12 14:38 UTC, alexs-mparticle commented on src/batchUploader.ts
> +export abstract class AsyncUploader {
If you're reusing the async uploader, let's just move them into their own file.

2024-02-12 14:38 UTC, alexs-mparticle commented on test/src/tests-audience-manager.ts
> +        expect(audienceManager.url).to.equal(userAudienceUrl);
Is this a duplicate test?

2024-02-12 14:41 UTC, rmi22186 commented on test/src/tests-audience-manager.ts
> +        expect(audienceManager.url).to.equal(userAudienceUrl);
Good catch

2024-02-12 14:46 UTC, alexs-mparticle commented on src/batchUploader.ts
> +export abstract class AsyncUploader {
Let's do it!

2024-02-13 21:41 UTC, alexs-mparticle requested changes

2024-02-13 21:41 UTC, alexs-mparticle commented on test/src/tests-audience-manager.ts
> +        const newLogger:SDKLoggerApi = new Logger(window.mParticle.config);
```suggestion
        const newLogger: SDKLoggerApi = new Logger(window.mParticle.config);
```

2024-02-13 21:44 UTC, alexs-mparticle approved these changes

2024-02-14 13:28 UTC, BrandonStalnaker reviewed
Looks good just 1 minor thing

2024-02-14 13:28 UTC, BrandonStalnaker commented on src/identity.js
> +             * @return {Object} an array with user segments????
comments probably need cleaned up here?

2024-02-16 00:31 UTC, rmi22186 commented
@BrandonStalnaker i updated.  please take another look.

2024-02-20 19:24 UTC, BrandonStalnaker commented on src/audienceManager.ts
> +    Unknown = 'unkown',
misspelling?

2024-02-26 15:01 UTC, rmi22186 commented on src/audienceManager.ts
> +    Unknown = 'unkown',
fixed

2024-02-29 14:02 UTC, merged