refactor: Migrate Consent State Persistence Methods
mParticle/mparticle-web-sdk pull request #877
Opened 2024-04-26 17:59 UTC by alexs-mparticle

## Instructions
 1. PR target branch should be against `development`
 2. PR title name should follow this format: https://github.com/mParticle/mparticle-workflows/blob/main/.github/workflows/pr-title-check.yml
 3. PR branch prefix should follow this format: https://github.com/mParticle/mparticle-workflows/blob/main/.github/workflows/pr-branch-check-name.yml

 ## Summary
 - Migrates Persistence methods for Consent State to Store

 ## Testing Plan
 - [x] Was this tested locally? If not, explain why.
 - Run through the automated tests
 - Smoke test a new, anonymous user session in a sample app, then attempt to add consent states
 - Subsequent events should have updated consent state properties
 - Refreshing the app should retain the new consent states
 - There should be no changes to expected behavior

 ## Reference Issue (For mParticle employees only.  Ignore if you are an outside contributor)
 - Closes https://go.mparticle.com/work/SQDSDKS-6411

2024-04-29 18:28 UTC, rmi22186 approved these changes

2024-04-29 18:57 UTC, rmi22186 approved these changes

2024-05-29 15:03 UTC, rmi22186 requested changes

2024-05-29 16:16 UTC, alexs-mparticle commented on src/store.ts
> +            );
It was. in this PR, I reorganized some of the methods.

2024-05-29 16:18 UTC, rmi22186 commented on src/store.ts
> +            );
i definitely missed that

2024-05-29 16:18 UTC, rmi22186 approved these changes

2024-06-04 19:48 UTC, merged

2024-06-04 19:54 UTC, mparticle-automation commented
:tada: This PR is included in version 2.26.8 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@mparticle/web-sdk/v/2.26.8)
- [GitHub release](https://github.com/mParticle/mparticle-web-sdk/releases/tag/v2.26.8)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: