Refactor/sqdsdks 6565 identity api client send identity request rob
mParticle/mparticle-web-sdk pull request #921
Opened 2024-09-17 01:44 UTC by rmi22186

## Instructions
 1. PR target branch should be against `development`
 2. PR title name should follow this format: https://github.com/mParticle/mparticle-workflows/blob/main/.github/workflows/pr-title-check.yml
 3. PR branch prefix should follow this format: https://github.com/mParticle/mparticle-workflows/blob/main/.github/workflows/pr-branch-check-name.yml

 ## Summary
Fix integration tests due to XHR --> Fetch 

 ## Testing Plan
 - [X] Was this tested locally? If not, explain why. - Unit tests fix up

 ## Reference Issue (For mParticle employees only.  Ignore if you are an outside contributor)
 - Closes https://go.mparticle.com/work/REPLACEME

2024-09-17 15:22 UTC, alexs-mparticle requested changes

2024-09-17 15:22 UTC, alexs-mparticle commented on test/src/config/utils.js
> +    fetchMockSuccess = function (url, body) {
Add the Cleanup Ticket here so we can search for it

2024-09-17 15:22 UTC, alexs-mparticle commented on test/src/config/utils.js
> +    },
Add the Cleanup Ticket here so we can search for it

2024-09-17 15:22 UTC, alexs-mparticle commented on test/src/tests-consent.ts
> +        debugger;
Remove this

2024-09-17 15:22 UTC, alexs-mparticle commented on test/src/tests-consent.ts
> +        // })
Remove

2024-09-17 15:22 UTC, alexs-mparticle commented on test/src/tests-consent.ts
> +        })
Add Catch

2024-09-17 15:22 UTC, alexs-mparticle commented on test/src/tests-consent.ts
> +        })
Add Catch

2024-09-17 15:22 UTC, alexs-mparticle commented on test/src/tests-cookie-syncing.js
> +        // mockServer.restore();
Remove

2024-09-17 15:22 UTC, alexs-mparticle commented on test/src/tests-cookie-syncing.js
> +        })
Add Catch

2024-09-17 15:22 UTC, alexs-mparticle commented on test/src/tests-cookie-syncing.js
> +                // mockServer.requests = [];
Remove

2024-09-17 15:22 UTC, alexs-mparticle commented on test/src/tests-cookie-syncing.js
> +            setTimeout(function() {
Let's leave a note to explain why we're doing a setTimeout

2024-09-17 15:22 UTC, alexs-mparticle commented on test/src/tests-cookie-syncing.js
> +        })
Add catch

2024-09-17 15:22 UTC, alexs-mparticle commented on test/src/tests-cookie-syncing.js
> +        })
Add catch

2024-09-17 15:22 UTC, alexs-mparticle commented on test/src/tests-cookie-syncing.js
> +                const data1 = mParticle
I think we should add a note to explain why we're doing a setTimeout

2024-09-17 15:22 UTC, alexs-mparticle commented on test/src/tests-cookie-syncing.js
> +                    mParticle.getInstance()._Store.configurationLoaded === true
Should we make this a utility function?

2024-09-17 15:22 UTC, alexs-mparticle commented on test/src/tests-cookie-syncing.js
> +                setTimeout(function() {
Let's explain why we're doing a set timeout

2024-09-17 15:22 UTC, alexs-mparticle commented on test/src/tests-cookie-syncing.js
> +        })
Add catch

2024-09-17 15:22 UTC, alexs-mparticle commented on test/src/tests-cookie-syncing.js
> +        })
Add catch

2024-09-17 15:22 UTC, alexs-mparticle commented on test/src/tests-cookie-syncing.js
> +        })
Add catch

2024-10-09 15:44 UTC, rmi22186 commented
closing in favor of https://github.com/mParticle/mparticle-web-sdk/pull/930

2024-10-09 15:44 UTC, closed without merging