fix: Support capturing click ids as custom flags in commerce events
mParticle/mparticle-web-sdk pull request #939
Opened 2024-10-24 20:25 UTC by rmi22186

## Instructions
 1. PR target branch should be against `development`
 2. PR title name should follow this format: https://github.com/mParticle/mparticle-workflows/blob/main/.github/workflows/pr-title-check.yml
 3. PR branch prefix should follow this format: https://github.com/mParticle/mparticle-workflows/blob/main/.github/workflows/pr-branch-check-name.yml

 ## Summary
- Commerce events were having the custom flags for click ids supplanted completely by custom flags that were being passed from the user. This PR fixes that. Instead we `extend` the custom flags to include both the custom flags created by `createEventObject` as well as what is passed by the user, with the flags passed by the user taken as priority.

 ## Testing Plan
Added unit tests for ecommerce and page view, as well as an additional for custom events

 ## Reference Issue (For mParticle employees only.  Ignore if you are an outside contributor)
 - Closes https://go.mparticle.com/work/SQDSDKS-6889

2024-10-24 20:33 UTC, alexs-mparticle requested changes

2024-10-24 20:33 UTC, alexs-mparticle commented on test/src/tests-integration-capture.ts
> +            {'Facebook.ClickId': 'passed-in',}
```suggestion
            { 'Facebook.ClickId': 'passed-in' },
```

2024-10-24 20:33 UTC, alexs-mparticle commented on test/src/tests-integration-capture.ts
> +        const initialTimestamp = window.mParticle.getInstance()._IntegrationCapture.initialTimestamp;
I see you're pulling this value but not using it anywhere.

2024-10-24 20:33 UTC, alexs-mparticle commented on test/src/tests-integration-capture.ts
> +            {'Facebook.ClickId': 'passed-in',}
```suggestion
            {'Facebook.ClickId': 'passed-in'},
```

2024-10-24 20:33 UTC, alexs-mparticle commented on test/src/tests-integration-capture.ts
> +describe.only('Integration Capture', () => {
```suggestion
describe('Integration Capture', () => {
```

2024-10-24 20:35 UTC, rmi22186 commented on test/src/tests-integration-capture.ts
> +        const initialTimestamp = window.mParticle.getInstance()._IntegrationCapture.initialTimestamp;
```suggestion
```

2024-10-24 20:35 UTC, alexs-mparticle commented on src/ecommerce.js
> +            baseEvent.CustomFlags = extend(baseEvent.CustomFlags, customFlags);
Can we use spread or the existing merge objects util? I'd like to get rid of the extend helper.

2024-10-24 20:48 UTC, alexs-mparticle approved these changes

2024-10-25 16:01 UTC, merged

2024-10-28 13:41 UTC, mparticle-automation commented
:tada: This PR is included in version 2.30.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@mparticle/web-sdk/v/2.30.2)
- [GitHub release](https://github.com/mParticle/mparticle-web-sdk/releases/tag/v2.30.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: